Document the user workflow
jitsuin-inc/archivist-shell pull request #2
Opened 2021-05-28 13:12 UTC by eccles

Problem:
Access to this repo must be available to any user on github.

Solution:
Describe in README the acceptable workflow using the 'fork' option in
the github UI.

Signed-off-by: eccles <phewlett76@gmail.com>

2021-05-28 14:12 UTC, jitsuineccles requested changes

2021-05-28 14:12 UTC, jitsuineccles commented on .github/CODEOWNERS
> +*  @JAG-UK @j-hartley @serhiy1 @leflambeur
I dont think this needed just yet. Anyway this file must be added in its own commit - please delete

2021-05-28 14:14 UTC, jitsuineccles approved these changes

2021-05-28 14:16 UTC, jitsuineccles requested changes

2021-05-28 14:16 UTC, jitsuineccles commented on README.md
> +git remote add upstream git@github.com:jitsuin-inc/archivist-shell.git
This should go after the clone step surely?

2021-05-28 14:20 UTC, jitsuineccles approved these changes

2021-05-28 14:20 UTC, jitsuineccles commented on README.md
> +git remote add upstream git@github.com:jitsuin-inc/archivist-shell.git
fixed

2021-06-01 09:49 UTC, leflambeur requested changes
Minor fixes - we need to Americanize things like synchronizing instead of synchronising

Worth doing a re-check of this and archivist-python to make sure it matches the docs style guide - link for ref. https://jitsuin-inc.github.io/rkvst-docs/contributing/formatting-content/style-guide/#grammar

Once you have reviewed it and updated those please squish the commits and I will approve it and merge

2021-06-01 10:34 UTC, leflambeur approved these changes

2021-06-01 10:34 UTC, leflambeur commented
LGTM and all checks passed, will merge now

2021-06-01 10:34 UTC, merged